_timer=0
_visible=false
_width=ds_grid_width(global.inventory)
_height=ds_grid_height(global.inventory)
_bounce=0
_box_size=36
_alpha=0
_temp_name=""
_press_cold_down=0
_inventory_grid_item_id=ds_grid_create(_width,_height)
ds_grid_set(global.inventory,0,0,"EternalRuby")